### ISSUE TITLE
Package dflydev/markdown is abandoned

### ISSUE THREAD

**Issue by itstueben** [sumpygump/holograph#2]
Its possible to change the Markdown Process? I get the following Message.
"Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead."

**Comment by sumpygump** [comment]
Thank you. I will look into this.

**Comment by sumpygump** [comment]
Fixed in master. I changed it to use `erusev/parsedown` instead of the abandoned `dflydev/markdown`
